env:
  contexts: {}
  parameters: {}
  vars: {}

jobs:
  - name: openapi
    type: openapi
    parameters:
      url: "file:///zap/wrk/config/openapi-enriched.json"

  - name: spider
    type: spider
    parameters:
      url: "http://zap-auth-proxy:80"
      maxDepth: 2
      maxChildren: 0

  - name: activeScan
    type: activeScan
    parameters:
      url: "http://zap-auth-proxy:80"
      policy: "Default Policy"

  - name: report
    type: report
    parameters:
      template: "modern"
      reportFile: "/zap/wrk/reports/report.baseline.json"
      reportTitle: "ZAP DAST Baseline Report"
