env:
  contexts:
    - name: "Default Context"
      urls:
        - "http://zap-auth-proxy:80/"
  parameters: {}
  vars: {}

jobs:
  - name: spider
    type: spider
    parameters:
      url: "http://zap-auth-proxy:80/api/v1/health"
      maxDepth: 3

  - name: activeScan
    type: activeScan
    parameters:
      url: "http://zap-auth-proxy:80/"
      policy: "Default Policy"

  - name: report
    type: report
    parameters:
      reportDir: "/zap/wrk/reports"
      reportFile: "report-enriched"
      reportTitle: "ZAP DAST Enriched Scan"
